name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.x', '12.x' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin main
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: yarn
      env:
        NODE_ENV: development
    - name: Unit Tests
      run: yarn test:unit
      env:
        NODE_ENV: production
    - name: Git History Test
      run: yarn test:git-history
      env:
        NODE_ENV: production
    - name: Lockfile Lint Test
      run: yarn test:lockfile
      env:
        NODE_ENV: production
    - name: Lint
      run: yarn test:lint
      env:
        NODE_ENV: production
